/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ShortsRouteImport } from './routes/shorts'
import { Route as NewsRouteImport } from './routes/news'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TitleIdRouteImport } from './routes/title.$id'

const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist', path: '/watchlist', getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search', path: '/search', getParentRoute: () => rootRouteImport,
} as any)
const ShortsRoute = ShortsRouteImport.update({
  id: '/shorts', path: '/shorts', getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news', path: '/news', getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile', path: '/profile', getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/', path: '/', getParentRoute: () => rootRouteImport,
} as any)
const TitleIdRoute = TitleIdRouteImport.update({
  id: '/title/$id', path: '/title/$id', getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/watchlist': typeof WatchlistRoute
  '/shorts': typeof ShortsRoute
  '/news': typeof NewsRoute
  '/profile': typeof ProfileRoute
  '/title/$id': typeof TitleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/watchlist': typeof WatchlistRoute
  '/shorts': typeof ShortsRoute
  '/news': typeof NewsRoute
  '/profile': typeof ProfileRoute
  '/title/$id': typeof TitleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/watchlist': typeof WatchlistRoute
  '/shorts': typeof ShortsRoute
  '/news': typeof NewsRoute
  '/profile': typeof ProfileRoute
  '/title/$id': typeof TitleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/search' | '/watchlist' | '/shorts' | '/news' | '/profile' | '/title/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/search' | '/watchlist' | '/shorts' | '/news' | '/profile' | '/title/$id'
  id: '__root__' | '/' | '/search' | '/watchlist' | '/shorts' | '/news' | '/profile' | '/title/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SearchRoute: typeof SearchRoute
  WatchlistRoute: typeof WatchlistRoute
  ShortsRoute: typeof ShortsRoute
  NewsRoute: typeof NewsRoute
  ProfileRoute: typeof ProfileRoute
  TitleIdRoute: typeof TitleIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watchlist': {
      id: '/watchlist'; path: '/watchlist'; fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport; parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'; path: '/search'; fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport; parentRoute: typeof rootRouteImport
    }
    '/shorts': {
      id: '/shorts'; path: '/shorts'; fullPath: '/shorts'
      preLoaderRoute: typeof ShortsRouteImport; parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'; path: '/news'; fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport; parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'; path: '/profile'; fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport; parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'; path: '/'; fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport; parentRoute: typeof rootRouteImport
    }
    '/title/$id': {
      id: '/title/$id'; path: '/title/$id'; fullPath: '/title/$id'
      preLoaderRoute: typeof TitleIdRouteImport; parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute,
  SearchRoute,
  WatchlistRoute,
  ShortsRoute,
  NewsRoute,
  ProfileRoute,
  TitleIdRoute,
}

export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
